# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c68084d31b4fe5b6f38a2f8af2e6f09a7d3458dd6537448904849b108d7a37dfa189e4bfce7175481a53125c083d899d1e48092b8fa8992f6bd0100426198e01

test:
  secret_key_base: 93199d66137cb2e0f06f3f003c4b798d234faf3d0f05c7d9ce0473f923218eeefa2cc174a65067a6355146803d63b50219d4fb0f696edff60b743936bce1d842

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
